from abc import ABC, abstractmethod


class StorageStrategy(ABC):
    """Storage strategy interface. We use this storage strategy to save and get the url of documents.
    This is especially useful for the image generated by the stable diffusion model."""

    @abstractmethod
    def save(self, filename, data):
        pass

    @abstractmethod
    def get_url(self, filename):
        pass
